export const SIGNUP_SUCCESSFUL = "SIGNUP_SUCCESSFUL";
export const SIGNIN_SUCCESSFUL = "SIGNIN_SUCCESSFUL";
export const SIGN_OUT_SUCCESSFUL = "SIGN_OUT_SUCCESSFUL";
export const GROUP_CREATED_SUCCESSFULLY = "GROUP_CREATED_SUCCESSFULLY";
export const GROUPS_RETRIEVED_SUCCESSFULLY = "GROUPS_RETRIEVED_SUCCESSFULLY";
export const SIGNOUT_SUCCESSFUL = "SIGNOUT_SUCCESSFUL";
